ruby install update

diff --git a/Jenkinsfile_CNP b/Jenkinsfile_CNP
--- a/Jenkinsfile_CNP
+++ b/Jenkinsfile_CNP
@@ -52,36 +52,41 @@ withPipeline(type, product, component) {
     env.DWP_API_ENABLED='false'
 
 
-      before('build') {
-        sh script:"""#!/bin/bash -l
-            set +x
-            source /usr/local/rvm/scripts/rvm
-            rvm get stable
-            rvm install ruby-4.0.5
-            rvm use ruby-4.0.5 --default
+    def installRuby = {
+      sh script:"""#!/bin/bash -l
+        set +x
+        source /usr/local/rvm/scripts/rvm
+        rvm install ruby-4.0.5
+        rvm use ruby-4.0.5 --default
         """, label: 'Ruby version install'
-      }
-
-      before('test') {
-        sh script:"""
-            mkdir -p ~/.local/bin
-            corepack enable --install-directory ~/.local/bin
-            export PATH=~/.local/bin:\$PATH
-            env AZURE_CONFIG_DIR=/opt/jenkins/.azure-nonprod az acr login --name hmctsprod --subscription DCD-CNP-PROD
-            yarn install
-
-            docker inspect hmctsprod.azurecr.io/imported/postgres:16-alpine > /dev/null 2>&1 || docker pull hmctsprod.azurecr.io/imported/postgres:16-alpine
-            docker stop hwf-test-postgres && docker rm hwf-test-postgres || echo 'Ignoring failure in stopping old postgres'
-            docker run --rm --name hwf-test-postgres --publish 5421:5432 -e POSTGRES_PASSWORD=postgres -d hmctsprod.azurecr.io/imported/postgres:16-alpine
-        """, label: 'Start test postgres'
-
-        rubyBuilder.bundle("exec rails db:create db:schema:load")
-        rubyBuilder.bundle("install")
-        rubyBuilder.bundle("exec rake assets:precompile")
     }
 
-    afterAlways('smokeTest') {
-        sh script: "docker stop hwf-test-postgres && docker rm hwf-test-postgres || echo 'Ignoring failure in stopping postgres'",
-            label: "docker stop hwf-test-postgres"
-    }
+    before('build') { installRuby() }
+    before('smoketest:preview') { installRuby() }
+    before('smoketest:aat') { installRuby() }
+    before('functionalTest:preview') { installRuby() }
+    before('functionalTest:aat') { installRuby() }
+
+    before('test') {
+      sh script:"""
+          mkdir -p ~/.local/bin
+          corepack enable --install-directory ~/.local/bin
+          export PATH=~/.local/bin:\$PATH
+          env AZURE_CONFIG_DIR=/opt/jenkins/.azure-nonprod az acr login --name hmctsprod --subscription DCD-CNP-PROD
+          yarn install
+
+          docker inspect hmctsprod.azurecr.io/imported/postgres:16-alpine > /dev/null 2>&1 || docker pull hmctsprod.azurecr.io/imported/postgres:16-alpine
+          docker stop hwf-test-postgres && docker rm hwf-test-postgres || echo 'Ignoring failure in stopping old postgres'
+          docker run --rm --name hwf-test-postgres --publish 5421:5432 -e POSTGRES_PASSWORD=postgres -d hmctsprod.azurecr.io/imported/postgres:16-alpine
+      """, label: 'Start test postgres'
+
+      rubyBuilder.bundle("exec rails db:create db:schema:load")
+      rubyBuilder.bundle("install")
+      rubyBuilder.bundle("exec rake assets:precompile")
+  }
+
+  afterAlways('smokeTest') {
+      sh script: "docker stop hwf-test-postgres && docker rm hwf-test-postgres || echo 'Ignoring failure in stopping postgres'",
+          label: "docker stop hwf-test-postgres"
+  }
 }
